# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=200)),
                ('is_approve', models.BooleanField(default=False)),
                ('is_in_translate', models.BooleanField(default=False)),
            ],
        ),
    ]
