# Generated by Django 2.1.1 on 2018-09-22 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_approve', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 9, 22, 20, 9, 12, 92564))),
            ],
        ),
    ]
