# Generated by Django 2.1.1 on 2018-09-23 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_auto_20180923_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 13, 54, 56, 852837)),
        ),
        migrations.RemoveField(
            model_name='dictionaries',
            name='language',
        ),
        migrations.AddField(
            model_name='dictionaries',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='word.Languages'),
        ),
    ]
