# Generated by Django 2.1.1 on 2018-09-23 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0006_auto_20180923_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaries',
            name='language_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_to', to='word.Languages'),
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 14, 5, 35, 895954)),
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_from', to='word.Languages'),
        ),
    ]
