# Generated by Django 2.1.1 on 2018-09-23 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0008_auto_20180923_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translate_from', to='word.Languages'),
        ),
        migrations.AddField(
            model_name='translate',
            name='language_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translate_to', to='word.Languages'),
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 19, 56, 34, 944980)),
        ),
    ]
