# Generated by Django 2.1.1 on 2018-09-23 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0009_auto_20180923_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaries',
            name='words',
        ),
        migrations.AddField(
            model_name='dictionaries',
            name='translate',
            field=models.ManyToManyField(to='word.Translate'),
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 21, 25, 34, 838862)),
        ),
    ]
