# Generated by Django 2.1.1 on 2018-09-23 19:21

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0010_auto_20180923_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaries',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 23, 22, 21, 44, 338195)),
        ),
    ]
