# Generated by Django 2.1.3 on 2019-01-21 17:06

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('word', '0015_auto_20190107_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsStudied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2019, 1, 21, 20, 6, 41, 871128))),
                ('progress', models.IntegerField(default=0)),
                ('translate', models.ManyToManyField(to='word.Translate')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='dictionaries',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 20, 6, 41, 869495)),
        ),
    ]
